services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 2s
      retries: 15

  etl:
    build: ./transformer
    depends_on:
      - db
    volumes:
      - ./mydata:/mydata

  scrape:
    build: ./scrape
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./mydata:/mydata

volumes:
  pgdata:
