services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
#      - ./mydata:/var/lib/postgresql/data

  etl:
    build: ./etl
    depends_on:
      - db

#  scrape:
#    depends_on:
#      - db

