FROM pgvector/pgvector:pg18-trixie

# Set environment variables
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=pass
ENV PGDATA=/var/lib/postgresql/data
ENV DB_HOST=localhost

# Install basic dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install ssh
RUN apt-get update && apt-get install -y openssh-server 
RUN mkdir -p /var/run/sshd

# Create working directories and req files
RUN mkdir -p /mydata /etl /scrape
COPY ./transformer/requirements.txt /etl/requirements.txt
COPY ./scrape/requirements.txt /scrape/requirements.txt

# Install requirements
RUN pip3 install --no-cache-dir --break-system-packages -r ./transformer/requirements.txt
RUN pip3 install --break-system-packages -r ./scrape/requirements.txt
RUN apt-get update && apt-get install -y vim
RUN apt-get update && apt-get install -y openssh-client
RUN apt-get install -y tmux

# Copy files
COPY ./transformer /etl
COPY ./scrape /scrape
COPY ./db/init /docker-entrypoint-initdb.d
COPY ./mydata /mydata


# Use the startup script as entrypoint
COPY ./startup.sh /startup.sh
RUN chmod +x /startup.sh
CMD ["/startup.sh"]
